drop table if exists cs_instr;
drop table if exists cs_instri;
create table cs_instr (id int,name string,soc decimal ,socdate date,bt bytes default '1'::bytes);
insert into cs_instr values(1,'xiaoming',50.0,date'2020-08-01');
insert into cs_instr values(2,'zhangsanbufulisi',100,date'2020-08-02');
insert into cs_instr values(3,'zheshiganshane',79.5,null);
insert into cs_instr values(4, null,80.5,date'2020-08-14');
insert into cs_instr values(5,'shuilaishuizhidao',50.1,date'2020-08-19');
insert into cs_instr values(6,'aishuaishuai',null,date'2020-09-10');
insert into cs_instr values(74,'a5bushia6',77.1,date'2020-08-15');
insert into cs_instr values(55,'****auddaua$',60.1,date'2020-08-20');
insert into cs_instr values(199,'aishuishusi',70.1,date'2020-08-29');
insert into cs_instr values(null,'buzhiduicuoai',88.1,date'2020-08-30');
create table cs_instri (id int,fname string);
insert into cs_instri values  (1,'a');
insert into cs_instri values (2,'b');
insert into cs_instri values (3,'c');
insert into cs_instri values (4,'d');
insert into cs_instri values (5,'e');
insert into cs_instri values (6,'f');
insert into cs_instri values (7,'g');
select instr('helloworld') from dual;
select instr('helloworld','he') from dual;
select instr('helloworld','nihaoya') from dual;
select instr('helloworld%','%') from dual;
select instr('helloworld!','!') from dual;
select instr('helloworld@','@') from dual;
select instr('helloworld#','#') from dual;
select instr('helloworld$','$') from dual;
select instr('helloworld￥','￥') from dual;
select instr('helloworld%','%') from dual;
select instr('helloworld^','^') from dual;
select instr('helloworld&','&') from dual;
select instr('helloworld*','*') from dual;
select instr('helloworld(','(') from dual;
select instr('helloworld)',')') from dual;
select instr('helloworld-','-') from dual;
select instr('helloworld+','+') from dual;
select instr('helloworld=','=') from dual;
select instr('helloworld{','{') from dual;
select instr('helloworld}','}') from dual;
select instr('helloworld【','【') from dual;
select instr('helloworld】','】') from dual;
select instr('helloworld[','[') from dual;
select instr('helloworld]',']') from dual;
select instr('helloworld\','\') from dual;
select instr('helloworld|','|') from dual;
select instr('helloworld:',':') from dual;
select instr('helloworld;',';') from dual;
select instr('helloworld?','?') from dual;
select instr('helloworld/','/') from dual;
select instr('helloworld>','>') from dual;
select instr('helloworld<','<') from dual;
select instr('helloworld','o',2) from dual;
select instr('helloworld','o',-2) from dual;
select instr('helloworld','o',0) from dual;
select instr('helloworld','o',2,1) from dual;
select instr('helloworld','o',2,0) from dual;
select instr('helloworld','o',2,-1) from dual;
select instr('helloworld','hello',2,-1) from dual;
select instr(date'2020-09-10','20',1,1) from dual;
select instr(date'2020-09-10','20','1','1') from dual;
select instr(date'2020-09-10',20,'1','1') from dual;
select instr(date'2020-09-10',20,'-1','1') from dual;
select instr(date'2020-09-10',20,'-1.5','1.8') from dual;
select instr(date'2020-09-10',20.00,'-1.5','1.8') from dual;
select instr(date'2020-09-10',20.00,'-1.5','1.8') from dual;
select instr(now(),sysdate,1,1) from dual;
select instr(date'2020-09-10',20:bytes,1,1) from dual;
select instr(date'2020-09-10',null,1,1) from dual;
select instr(date'2020-09-10',20,null,1) from dual;
select instr(date'2020-09-10',20,1,null) from dual;
select instr(date'2020-09-10',null,null,null) from dual;
select instr('2020-09-10',20,1.5,2) from dual;
select instr('2020-09-10',20.0,1.5,2) from dual;
select instr('2020-09-10 23:11:11',date'2020-09-10',1,1) from dual;
select instr('2020-09-10','2020'::bytes,1,1) from dual;
select instr('2020-09-10',null,1.5,2) from dual;
select instr('2020-09-10',20,null,2) from dual;
select instr('2020-09-10',20,1,null) from dual;
select instr('你好2022');
select instr('2020-09-10',null,null,null) from dual;
select instr(1.345,1.3,1,1) from dual;
select instr(1.345,'1.3',1,1) from dual;
select instr(1.345,'1.3',-1,1) from dual;
select instr(2000.00,date'2000',1,1) from dual;
select instr(1.345,'1'::bytes,1,1) from dual;
select instr('1234'::bytes,'1',1,1 ) from dual;
select instr('2020-02-01'::bytes,date'2020',1,1 ) from dual;
select instr('1.678'::bytes,1.6,1,1) from dual;
select instr('你好2020'::bytes,'20',1,1) from dual;
select instr (id,1,1,1) from cs_instr;
select instr (id,1,-1,1) from cs_instr;
select instr (id,'1',1,1) from cs_instr;
select instr(name,'a',1,1) from cs_instr;
select instr(name,'a',-1,1) from cs_instr;
select instr(name,'$',-1,1) from cs_instr;
select instr(name,'*',1,1) from cs_instr;
select instr(name,1,1,1) from cs_instr;
select instr(name,'$','-1','1') from cs_instr;
select instr(name,'$','-1.5','1.5') from cs_instr;
select instr(soc,0.5,1,1) from cs_instr;
select instr(soc,0.5,-1,1) from cs_instr;
select instr(soc,'0.5',-1,1) from cs_instr;
select instr(socdate,'20',1,1)  from cs_instr;
select instr(socdate,'20',1,1) from cs_instr;
select instr(socdate,20,'-1.5','1.9') from cs_instr;
select instr(bt,1,1,1) from cs_instr;
select instr(bt,1,1,1) from cs_instr;
select instr(null,1,1,1) from cs_instr;
select instr(null,null,null,null) from cs_instr;
insert into cs_instr (id,soc)  select instr('hello world','he',1,1),instr('hello world','wo',1,1) from dual;
insert into cs_instr (id,soc)  select instr('hello world','he',1,1),instr('hello world','1',1,1) from dual;
insert into cs_instr (id,soc)  select instr('hello world','he',1,1),instr('hello world','1',-1,1) from dual;
insert into cs_instr(id,soc) values(instr('nihao','hao',1,1),instr('nihao','hao',1,1));
insert into cs_instr(id) values(instr('nihao','hao'));
update cs_instr set id=instr('hellowolrd',i'he',1,1) where instr(name,'a',1,1)=1;
delete from cs_instr where instr(name,'a',1,1)=1;
delete from cs_instr where substr(name,'a',instr(name,'a')) in (select pname from cs_instri);
alter table cs_instr  alter column id set default instr('helloworld','he');
select * from cs_instr where id < instr('helloworld','world');
select * from cs_instr where id > instr('helloworld','world');
select * from cs_instr where id = instr('helloworld','world');
select * from cs_instr where id between instr('helloworld','he') and instr('hellowrold','wo');
select instr(name,'a') from cs_instr union select instr(name,'z') from cs_instr;
select instr(name,'a') from cs_instr union all select instr(name,'z') from cs_instr;
select instr(name,'a') from cs_instr except select instr(name,'z') from cs_instr;
select instr(name,'a') from cs_instr intersect select instr(name,'z') from cs_instr;
select instr(name,'a') ,name from cs_instr order  by instr(name,'a') desc;
select instr(name,'a') ,name from cs_instr order  by instr(name,'a') asc;
select instr(name,'a'),name from cs_instr group by instr(name,'a'),name;
select * from cs_instr a inner join cs_instri b on  instr(a.name,'a')=instr(b.fname,'a');
select * from cs_instr a left outer join cs_instri b on  instr(a.name,'a')=instr(b.fname,'a');
select * from cs_instr a right outer join cs_instri b on  instr(a.name,'a')=instr(b.fname,'a');
select * from cs_instr a full outer join cs_instri b on  instr(a.name,'a')=instr(b.fname,'a');
select * from cs_instr where substr(name,1,1) in (select substr(fname,instr('abc','a')) from cs_instri);
select instr(soc,1)+instr(name,'a') from cs_instr;
select instr(soc,1)-instr(name,'a') from cs_instr;
select instr(soc,1)*instr(name,'a') from cs_instr;
select instr(soc,1)/instr(name,'a') from cs_instr;
select instr(substr(lpad(name,40000,'nihao'),1),name) from cs_instr;
SELECT SUBSTR('hello,world', 1, INSTR('hello,world', ',')-1) FROM DUAL;
select sum(instr(name,'a')) from cs_instr;
select max(instr(name,'a')) from cs_instr;
select min(instr(name,'a')) from cs_instr;
select count(instr(name,'a')) from cs_instr;
select instr('hello','lo')||instr('hello','h') from dual;
select lpad('nihao',instr('bbababbax','x'),' ') from dual;
select avg(instr(name,'a')) from cs_instr;
select trim(lpad('nihao',instr('bbababbax','x'),' ')) from dual;
select instrb('helloworld') from dual;
select instrb('helloworld','he') from dual;
select instrb('helloworld','nihaoya') from dual;
select instrb('helloworld%','%') from dual;
select instrb('helloworld!','!') from dual;
select instrb('helloworld@','@') from dual;
select instrb('helloworld#','#') from dual;
select instrb('helloworld$','$') from dual;
select instrb('helloworld￥','￥') from dual;
select instrb('helloworld%','%') from dual;
select instrb('helloworld^','^') from dual;
select instrb('helloworld&','&') from dual;
select instrb('helloworld*','*') from dual;
select instrb('helloworld(','(') from dual;
select instrb('helloworld)',')') from dual;
select instrb('helloworld-','-') from dual;
select instrb('helloworld+','+') from dual;
select instrb('helloworld=','=') from dual;
select instrb('helloworld{','{') from dual;
select instrb('helloworld}','}') from dual;
select instrb('helloworld【','【') from dual;
select instrb('helloworld】','】') from dual;
select instrb('helloworld[','[') from dual;
select instrb('helloworld]',']') from dual;
select instrb('helloworld\','\') from dual;
select instrb('helloworld|','|') from dual;
select instrb('helloworld:',':') from dual;
select instrb('helloworld;',';') from dual;
select instrb('helloworld?','?') from dual;
select instrb('helloworld/','/') from dual;
select instrb('helloworld>','>') from dual;
select instrb('helloworld<','<') from dual;
select instrb('helloworld','o',2) from dual;
select instrb('helloworld','o',-2) from dual;
select instrb('helloworld','o',0) from dual;
select instrb('helloworld','o',2,1) from dual;
select instrb('helloworld','o',2,0) from dual;
select instrb('helloworld','o',2,-1) from dual;
select instrb('helloworld','hello',2,-1) from dual;
select instrb(date'2020-09-10','20',1,1) from dual;
select instrb(date'2020-09-10','20','1','1') from dual;
select instrb(date'2020-09-10',20,'1','1') from dual;
select instrb(date'2020-09-10',20,'-1','1') from dual;
select instrb(date'2020-09-10',20,'-1.5','1.8') from dual;
select instrb(date'2020-09-10',20.00,'-1.5','1.8') from dual;
select instrb(date'2020-09-10',20.00,'-1.5','1.8') from dual;
select instrb(sysdate,date'2020-09-10',1,1) from dual;
select instrb(date'2020-09-10',20:bytes,1,1) from dual;
select instrb(date'2020-09-10',null,1,1) from dual;
select instrb(date'2020-09-10',20,null,1) from dual;
select instrb(date'2020-09-10',20,1,null) from dual;
select instrb(date'2020-09-10',null,null,null) from dual;
select instrb('2020-09-10',20,1.5,2) from dual;
select instrb('2020-09-10',20.0,1.5,2) from dual;
select instrb('2020-09-10',date'2020-09',1,1) from dual;
select instrb('2020-09-10','2020'::bytes,1,1) from dual;
select instrb('2020-09-10',null,1.5,2) from dual;
select instrb('2020-09-10',20,null,2) from dual;
select instrb('2020-09-10',20,1,null) from dual;
select instrb('你好2022')
select instrb('2020-09-10',null,null,null) from dual;
select instrb(1.345,1.3,1,1) from dual;
select instrb(1.345,'1.3',1,1) from dual;
select instrb(1.345,'1.3',-1,1) from dual;
select instrb(2000.00,date'2000',1,1) from dual;
select instrb(1.345,1::bytes,1,1) from dual;
select instrb('1234'::byteas,'1',1,1 ) from dual;
select instrb('2020-02-01'::byteas,date'2020',1,1 ) from dual;
select instrb('1.678'::byteas,1.6,1,1) from dual;
select instrb('你好2020'::bytes,'20',1,1) from dual;
select instr (id,1,1,1) from cs_instr;
select instr (id,1,-1,1) from cs_instr;
select instr (id,'1',1,1) from cs_instr;
select instrb(name,'a',1,1) from cs_instr;
select instrb(name,'a',-1,1) from cs_instr;
select instrb(name,'$',-1,1) from cs_instr;
select instrb(name,'*',1,1) from cs_instr;
select instrb(name,1,1,1) from cs_instr;
select instrb(name,'$','-1','1') from cs_instr;
select instrb(name,'$','-1.5','1.5') from cs_instr;
select instrb(soc,0.5,1,1) from cs_instr;
select instrb(soc,0.5,-1,1) from cs_instr;
select instrb(soc,'0.5',-1,1) from cs_instr;
select instrb(socdate,'20',1,1)  from cs_instr;
select instrb(socdate,'20',1,1) from cs_instr;
select instrb(socdate,20,'-1.5','1.9') from cs_instr;
select instrb(bt,1,1,1) from cs_instr;
select instrb(bt,1,1,1) from cs_instr;
select instrb(null,1,1,1) from cs_instr;
select instrb(null,null,null,null) from cs_instr;
insert into cs_instr (id,soc)  select instrb('hello world','he',1,1),instrb('hello world','wo',1,1) from dual;
insert into cs_instr (id,soc)  select instrb('hello world','he',1,1),instrb('hello world','1',1,1) from dual;
insert into cs_instr (id,soc)  select instrb('hello world','he',1,1),instrb('hello world','1',-1,1) from dual;
insert into cs_instrb(id,soc) values(instrb('nihao','hao',1,1)),instrb('nihao','hao',1,1)));
update cs_instr set id=instrb('hellowolrd',he,1,1) where instrb(name,'a',1,1)=1;
delete  from cs_instr where instrb(name,'a',1,1)=1;
delete  from cs_instr where substr(name,'a',instrb(name,'a')) in (select pname from cs_instri);
alter table cs_instr  alter column id default instrb('helloworld','he');
select * from cs_instr where id < instrb('helloworld','world');
select * from cs_instr where id > instrb('helloworld','world');
select * from cs_instr where id = instrb('helloworld','world');
select * from cs_instr where id between instrb('helloworld','he') and instrb('hellowrold','wo');
select instrb(name,'a') from cs_instr union select instrb(name,'z') from cs_instr;
select instrb(name,'a') from cs_instr union all select instrb(name,'z') from cs_instr;
select instrb(name,'a') from cs_instr except select instrb(name,'z') from cs_instr;
select instrb(name,'a') from cs_instr intersect select instrb(name,'z') from cs_instr;
select instrb(name,'a') ,name from cs_instr order  by instrb(name,'a') desc;
select instrb(name,'a') ,name from cs_instr order  by instrb(name,'a') asc;
select instrb(name,'a'),name from cs_instr group by instrb(name,'a'),name;
select * from cs_instr a inner join cs_instri b on  instrb(a.name,'a')=instrb(b.fname,'a');
select * from cs_instr a left outer join cs_instri b on  instrb(a.name,'a')=instrb(b.fname,'a');
select * from cs_instr a right outer join cs_instri b on  instrb(a.name,'a')=instrb(b.fname,'a');
select * from cs_instr a full outer join cs_instri b on  instrb(a.name,'a')=instrb(b.fname,'a');
select * from cs_instr where substr(name,1,1) in (select substr(fname,instrb('abc','a')) from cs_instri);
select instrb(soc,1)+instrb(name,'a') from cs_instr;
select instrb(soc,1)-instrb(name,'a') from cs_instr;
select instrb(soc,1)*instrb(name,'a') from cs_instr;
select instrb(soc,1)/instrb(name,'a') from cs_instr;
select instrb(substr(lpad(name,40000,'nihao'),1,1), from cs_instr;
SELECT SUBSTR('hello,world', 1, instrb('hello,world', ',')-1) FROM DUAL;
select instrb('hello','lo')||instrb('hello','h') from dual;
select sum(instrb(name,'a')) from cs_instr;
select max(instrb(name,'a')) from cs_instr;
select min(instrb(name,'a')) from cs_instr;
select avg(instrb(name,'a')) from cs_instr;
select count(instrb(name,'a')) from cs_instr;
select lpad('nihao',instrb('bbababbax','x'),' ') from dual;
select trim(lpad('nihao',instrb('bbababbax','x'),' ')) from dual;
select instrc('helloworld') from dual;
select instrc('helloworld','he') from dual;
select instrc('helloworld','nihaoya') from dual;
select instrc('helloworld%','%') from dual;
select instrc('helloworld!','!') from dual;
select instrc('helloworld@','@') from dual;
select instrc('helloworld#','#') from dual;
select instrc('helloworld$','$') from dual;
select instrc('helloworld￥','￥') from dual;
select instrc('helloworld%','%') from dual;
select instrc('helloworld^','^') from dual;
select instrc('helloworld&','&') from dual;
select instrc('helloworld*','*') from dual;
select instrc('helloworld(','(') from dual;
select instrc('helloworld)',')') from dual;
select instrc('helloworld-','-') from dual;
select instrc('helloworld+','+') from dual;
select instrc('helloworld=','=') from dual;
select instrc('helloworld{','{') from dual;
select instrc('helloworld}','}') from dual;
select instrc('helloworld【','【') from dual;
select instrc('helloworld】','】') from dual;
select instrc('helloworld[','[') from dual;
select instrc('helloworld]',']') from dual;
select instrc('helloworld\','\') from dual;
select instrc('helloworld|','|') from dual;
select instrc('helloworld:',':') from dual;
select instrc('helloworld;',';') from dual;
select instrc('helloworld?','?') from dual;
select instrc('helloworld/','/') from dual;
select instrc('helloworld>','>') from dual;
select instrc('helloworld<','<') from dual;
select instrc('helloworld','o',2) from dual;
select instrc('helloworld','o',-2) from dual;
select instrc('helloworld','o',0) from dual;
select instrc('helloworld','o',2,1) from dual;
select instrc('helloworld','o',2,0) from dual;
select instrc('helloworld','o',2,-1) from dual;
select instrc('helloworld','hello',2,-1) from dual;
select instrc(date'2020-09-10','20',1,1) from dual;
select instrc(date'2020-09-10','20','1','1') from dual;
select instrc(date'2020-09-10',20,'1','1') from dual;
select instrc(date'2020-09-10',20,'-1','1') from dual;
select instrc(date'2020-09-10',20,'-1.5','1.8') from dual;
select instrc(date'2020-09-10',20.00,'-1.5','1.8') from dual;
select instrc(date'2020-09-10',20.00,'-1.5','1.8') from dual;
select instrc(sysdate,date'2020-09-10',1,1) from dual;
select instrc(date'2020-09-10',20:bytes,1,1) from dual;
select instrc(date'2020-09-10',null,1,1) from dual;
select instrc(date'2020-09-10',20,null,1) from dual;
select instrc(date'2020-09-10',20,1,null) from dual;
select instrc(date'2020-09-10',null,null,null) from dual;
select instrc('2020-09-10',20,1.5,2) from dual;
select instrc('2020-09-10',20.0,1.5,2) from dual;
select instrc('2020-09-10',date'2020-09',1,1) from dual;
select instrc('2020-09-10','2020'::bytes,1,1) from dual;
select instrc('2020-09-10',null,1.5,2) from dual;
select instrc('2020-09-10',20,null,2) from dual;
select instrc('2020-09-10',20,1,null) from dual;
select instrc('你好2022')
select instrc('2020-09-10',null,null,null) from dual;
select instrc(1.345,1.3,1,1) from dual;
select instrc(1.345,'1.3',1,1) from dual;
select instrc(1.345,'1.3',-1,1) from dual;
select instrc(2000.00,date'2000',1,1) from dual;
select instrc(1.345,1::bytes,1,1) from dual;
select instrc('1234'::byteas,'1',1,1 ) from dual;
select instrc('2020-02-01'::byteas,date'2020',1,1 ) from dual;
select instrc('1.678'::byteas,1.6,1,1) from dual;
select instrc('你好2020'::bytes,'20',1,1) from dual;
select instr (id,1,1,1) from cs_instr;
select instr (id,1,-1,1) from cs_instr;
select instr (id,'1',1,1) from cs_instr;
select instrc(name,'a',1,1) from cs_instr;
select instrc(name,'a',-1,1) from cs_instr;
select instrc(name,'$',-1,1) from cs_instr;
select instrc(name,'*',1,1) from cs_instr;
select instrc(name,1,1,1) from cs_instr;
select instrc(name,'$','-1','1') from cs_instr;
select instrc(name,'$','-1.5','1.5') from cs_instr;
select instrc(soc,0.5,1,1) from cs_instr;
select instrc(soc,0.5,-1,1) from cs_instr;
select instrc(soc,'0.5',-1,1) from cs_instr;
select instrc(socdate,'20',1,1)  from cs_instr;
select instrc(socdate,'20',1,1) from cs_instr;
select instrc(socdate,20,'-1.5','1.9') from cs_instr;
select instrc(bt,1,1,1) from cs_instr;
select instrc(bt,1,1,1) from cs_instr;
select instrc(null,1,1,1) from cs_instr;
select instrc(null,null,null,null) from cs_instr;
insert into cs_instr (id,soc)  select instrc('hello world','he',1,1),instrc('hello world','wo',1,1) from dual;
insert into cs_instr (id,soc)  select instrc('hello world','he',1,1),instrc('hello world','1',1,1) from dual;
insert into cs_instr (id,soc)  select instrc('hello world','he',1,1),instrc('hello world','1',-1,1) from dual;
insert into cs_instrc(id,soc) values(instrc('nihao','hao',1,1)),instrc('nihao','hao',1,1)));
update cs_instr set id=instrc('hellowolrd',he,1,1) where instrc(name,'a',1,1)=1;
delete  from cs_instr where instrc(name,'a',1,1)=1;
delete  from cs_instr where substr(name,'a',instrc(name,'a')) in (select pname from cs_instri);
alter table cs_instr  alter column id default instrc('helloworld','he');
select * from cs_instr where id < instrc('helloworld','world');
select * from cs_instr where id > instrc('helloworld','world');
select * from cs_instr where id = instrc('helloworld','world');
select * from cs_instr where id between instrc('helloworld','he') and instrc('hellowrold','wo');
select instrc(name,'a') from cs_instr union  select instrc(name,'z') from cs_instr;
select instrc(name,'a') from cs_instr union all select instrc(name,'z') from cs_instr;
select instrc(name,'a') from cs_instr except select instrc(name,'z') from cs_instr;
select instrc(name,'a') from cs_instr intersect select instrc(name,'z') from cs_instr;
select instrc(name,'a') ,name from cs_instr order  by instrc(name,'a') desc;
select instrc(name,'a') ,name from cs_instr order  by instrc(name,'a') asc;
select instrc(name,'a'),name from cs_instr group by instrc(name,'a'),name;
select * from cs_instr a inner join cs_instri b on  instrc(a.name,'a')=instrc(b.fname,'a');
select * from cs_instr a left outer join cs_instri b on  instrc(a.name,'a')=instrc(b.fname,'a');
select * from cs_instr a right outer join cs_instri b on  instrc(a.name,'a')=instrc(b.fname,'a');
select * from cs_instr a full outer join cs_instri b on  instrc(a.name,'a')=instrc(b.fname,'a');
select * from cs_instr where substr(name,1,1) in (select substr(fname,instrc('abc','a')) from cs_instri);
select instrc(soc,1)+instrc(name,'a') from cs_instr;
select instrc(soc,1)-instrc(name,'a') from cs_instr;
select instrc(soc,1)*instrc(name,'a') from cs_instr;
select instrc(soc,1)/instrc(name,'a') from cs_instr;
select instrc(substr(lpad(name,40000,'nihao'),1,1), from cs_instr;
SELECT SUBSTR('hello,world', 1, instrc('hello,world', ',')-1) FROM DUAL;
select instrc('hello','lo')||instr('hello','h') from dual;
select sum(instrc(name,'a')) from cs_instr;
select max(instrc(name,'a')) from cs_instr;
select min(instrc(name,'a')) from cs_instr;
select avg(instrc(name,'a')) from cs_instr;
select count(instrc(name,'a')) from cs_instr;
select lpad('nihao',instrc('bbababbax','x'),' ') from dual;
select trim(lpad('nihao',instrc('bbababbax','x'),' ')) from dual;
drop table cs_instr;
drop table cs_instri;
