# -*- coding:utf8 -*-
#!/usr/bin/python


import os

basename=os.getcwd()
logfile=os.path.join(basename,"regression.log")


## 2 region 3 center 331 deloyment zone config
initha331 = """ALTER RANGE default CONFIGURE ZONE USING num_replicas = {3}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1},''+region=xibei'':{2}}}'; ALTER DATABASE system CONFIGURE ZONE USING num_replicas = {3}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1},''+region=xibei'':{2}}}';ALTER RANGE liveness CONFIGURE ZONE USING num_replicas = {3}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1},''+region=xibei'':{2}}}';ALTER RANGE meta CONFIGURE ZONE USING num_replicas = {3}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1},''+region=xibei'':{2}}}';ALTER RANGE system CONFIGURE ZONE USING num_replicas = {3}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1},''+region=xibei'':{2}}}';ALTER TABLE system.public.replication_constraint_stats CONFIGURE ZONE USING  num_replicas = {3}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1},''+region=xibei'':{2}}}';ALTER TABLE system.public.replication_stats CONFIGURE ZONE USING num_replicas = {3}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1},''+region=xibei'':{2}}}';ALTER TABLE system.public.tenant_usage CONFIGURE ZONE USING num_replicas = {3}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1},''+region=xibei'':{2}}}';"""

## primary room deloyment zone config
initrid1 = """ALTER RANGE default CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huabei'':{0}}}'; ALTER DATABASE system CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huabei'':{0}}}';ALTER RANGE liveness CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huabei'':{0}}}';ALTER RANGE meta CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huabei'':{0}}}';ALTER RANGE system CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huabei'':{0}}}';ALTER TABLE system.public.replication_constraint_stats CONFIGURE ZONE USING  num_replicas = {1}, constraints = '{{''+region=huabei'':{0}}}';ALTER TABLE system.public.replication_stats CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huabei'':{0}}}';ALTER TABLE system.public.tenant_usage CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huabei'':{0}}}';"""

# local backroom deloyment zone config
initrid2 = """ALTER RANGE default CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huanan'':{0}}}';ALTER DATABASE system CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huanan'':{0}}}';ALTER RANGE liveness CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huanan'':{0}}}';ALTER RANGE meta CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huanan'':{0}}}';ALTER RANGE system CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huanan'':{0}}}';ALTER TABLE system.public.replication_constraint_stats CONFIGURE ZONE USING  num_replicas = {1}, constraints = '{{''+region=huanan'':{0}}}';ALTER TABLE system.public.replication_stats CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huanan'':{0}}}';ALTER TABLE system.public.tenant_usage CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=huanan'':{0}}}';"""

# remote room deloyment zone config
initrid3 = """ALTER RANGE default CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=xibei'':{0}}}';ALTER DATABASE system CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=xibei'':{0}}}';ALTER RANGE liveness CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=xibei'':{0}}}';ALTER RANGE meta CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=xibei'':{0}}}';ALTER RANGE system CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=xibei'':{0}}}';ALTER TABLE system.public.replication_constraint_stats CONFIGURE ZONE USING  num_replicas = {1}, constraints = '{{''+region=xibei'':{0}}}';ALTER TABLE system.public.replication_stats CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=xibei'':{0}}}';ALTER TABLE system.public.tenant_usage CONFIGURE ZONE USING num_replicas = {1}, constraints = '{{''+region=xibei'':{0}}}';"""

# all back room deloyment zone config
initrid23 = """ALTER RANGE default CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huanan'':{0},''+region=xibei'':{1}}}';ALTER DATABASE system CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huanan'':{0},''+region=xibei'':{1}}}';ALTER RANGE liveness CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huanan'':{0},''+region=xibei'':{1}}}';ALTER RANGE meta CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huanan'':{0},''+region=xibei'':{1}}}';ALTER RANGE system CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huanan'':{0},''+region=xibei'':{1}}}';ALTER TABLE system.public.replication_constraint_stats CONFIGURE ZONE USING  num_replicas = {2}, constraints = '{{''+region=huanan'':{0},''+region=xibei'':{1}}}';ALTER TABLE system.public.replication_stats CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huanan'':{0},''+region=xibei'':{1}}}';ALTER TABLE system.public.tenant_usage CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huanan'':{0},''+region=xibei'':{1}}}';"""

# primary and local room zone config
initrid12 = """ALTER RANGE default CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1}}}';ALTER DATABASE system CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1}}}';ALTER RANGE liveness CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1}}}';ALTER RANGE meta CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1}}}';ALTER RANGE system CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1}}}';ALTER TABLE system.public.replication_constraint_stats CONFIGURE ZONE USING  num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1}}}';ALTER TABLE system.public.replication_stats CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1}}}';ALTER TABLE system.public.tenant_usage CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=huanan'':{1}}}';"""

# primary and remote room zone config
initrid13 = """ALTER RANGE default CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=xibei'':{1}}}';ALTER DATABASE system CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=xibei'':{1}}}';ALTER RANGE liveness CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=xibei'':{1}}}';ALTER RANGE meta CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=xibei'':{1}}}';ALTER RANGE system CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=xibei'':{1}}}';ALTER TABLE system.public.replication_constraint_stats CONFIGURE ZONE USING  num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=xibei'':{1}}}';ALTER TABLE system.public.replication_stats CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=xibei'':{1}}}';ALTER TABLE system.public.tenant_usage CONFIGURE ZONE USING num_replicas = {2}, constraints = '{{''+region=huabei'':{0},''+region=xibei'':{1}}}';"""
## check node status isnot live  for liveness
sqllive = "select t1.node_id, t1.address,t1.is_live from dbms_internal.gossip_nodes t1 left join dbms_internal.gossip_liveness t2 on t1.node_id = t2.node_id;"
#sqllive = "select t1.node_id, t1.address,t1.ranges,t1.is_live,t2.membership,t2.draining,t2.decommissioning from dbms_internal.gossip_nodes t1 left join dbms_internal.gossip_liveness t2 on t1.node_id = t2.node_id;"

lease_preference = " ALTER RANGE default CONFIGURE ZONE USING lease_preferences='[[+region={0}]]';ALTER DATABASE system CONFIGURE ZONE USING lease_preferences='[[+region={0}]]';ALTER RANGE liveness CONFIGURE ZONE USING lease_preferences='[[+region={0}]]';ALTER RANGE meta CONFIGURE ZONE USING lease_preferences='[[+region={0}]]';ALTER RANGE system CONFIGURE ZONE USING lease_preferences='[[+region={0}]]';ALTER TABLE system.public.replication_constraint_stats CONFIGURE ZONE USING  lease_preferences='[[+region={0}]]';ALTER TABLE system.public.replication_stats CONFIGURE ZONE USING lease_preferences='[[+region={0}]]';ALTER TABLE system.public.tenant_usage CONFIGURE ZONE USING lease_preferences='[[+region={0}]]';"
